CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  burger_name VARCHAR(255) NOT NULL,
  devoured BOOLEAN DEFAUlT false,
  timeCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);